# fly.toml app configuration file generated for skyhigh on 2023-08-24T11:49:32+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "skyhigh"
primary_region = "ams"
swap_size_mb = 256

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
